name: Upload coverage reports to Codecov

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  upload-coverage:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up R
        uses: r-lib/actions/setup-r@v2
        # Remove the 'with:' block if you don't need any options,
        # or ensure it has valid options like this:
        # with:
        #   r-version: '4.3' # Example: Use a specific R version

      - name: Install dependencies and self
        shell: bash
        run: |
          echo "Installing devtools and covr..."
          Rscript -e 'install.packages(c("devtools", "covr"), repos = "https://cloud.r-project.org")' || exit 1

          echo "Installing package dependencies..."
          Rscript -e 'devtools::install_deps(dependencies = TRUE)' || exit 1

          echo "Installing the current package (shannonR)..."
          Rscript -e 'devtools::install(".", dependencies = FALSE, upgrade = "never", build_vignettes = FALSE, INSTALL_opts = "--no-lock")' || exit 1

          echo "Installation complete."

      - name: Run tests and generate coverage
        shell: Rscript {0}
        run: |
          library(shannonR)
          covr::codecov()

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v5
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          slug: urppeia/shannonR
