name: Upload coverage reports to Codecov

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  upload-coverage:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up R
        uses: r-lib/actions/setup-r@v2
        with:
          # Optional: Specify R version, e.g., 'release', '4.3', '4.2'
          # r-version: 'release'

      - name: Install dependencies and self
        # Using Rscript with -e and piping the output to cat for better visibility
        # Also, adding --no-lock to install.packages to avoid renv interference if not intended
        run: |
          Rscript -e 'install.packages(c("devtools", "covr"))' --no-lock-dir
          Rscript -e 'devtools::install_deps(dependencies = TRUE)'
          # Use verbose output for devtools::install to aid debugging
          Rscript -e 'devtools::install(".", dependencies = FALSE, upgrade = "never", build_vignettes = FALSE, INSTALL_opts = "--no-lock")'
        # The default shell for R actions is Rscript {0}, so explicitly setting it is good practice
        shell: Rscript {0}

      - name: Run tests and generate coverage
        run: |
          # Ensure your package is loaded before running covr
          Rscript -e 'library(shannonR); covr::codecov()'
        shell: Rscript {0}

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v5
        with:
          token: ${{ secrets.CODECOV_TOKEN }}  # Optional for public repo
          slug: urppeia/shannonR
