name: Upload coverage reports to Codecov

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  upload-coverage:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up R
        uses: r-lib/actions/setup-r@v2

      - name: Install dependencies
        run: |
          install.packages("devtools")
          devtools::install_deps(dependencies = TRUE)
          install.packages("covr")
        shell: Rscript {0}

      - name: Run tests and generate coverage
        run: covr::codecov()
        shell: Rscript {0}

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v5
        with:
          token: ${{ secrets.CODECOV_TOKEN }}  # Optional for public repo
          slug: urppeia/shannonR
