name: R-CMD-check-and-coverage

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
  workflow_dispatch: # Enables manual trigger button

jobs:
  R-CMD-check:
    runs-on: ${{ matrix.config.os }}
    name: ${{ matrix.config.os }} (${{ matrix.config.r }})
    strategy:
      matrix:
        config:
          - {os: ubuntu-latest, r: 'release'}
          - {os: macos-latest, r: 'release'}
          - {os: windows-latest, r: 'release'}
          - {os: ubuntu-latest, r: 'devel'}

    steps:
      - uses: actions/checkout@v4
      - uses: r-lib/actions/setup-r@v2
        with:
          r-version: ${{ matrix.config.r }}
      - name: Install renv
        run: |
          install.packages("renv")
        shell: Rscript {0}
      - name: Cache renv dependencies
        uses: actions/cache@v4
        with:
          path: ${{ env.R_RENV_PATHS_ROOT || '~/.local/share/renv' }}
          key: ${{ runner.os }}-renv-${{ hashFiles('renv.lock') }}
          restore-keys: ${{ runner.os }}-renv-
      - name: Restore renv dependencies
        run: |
          renv::restore()
        shell: Rscript {0}
      - uses: r-lib/actions/setup-r-dependencies@v2
        with:
          extra-packages: any::rcmdcheck
          needs: check
      - uses: r-lib/actions/check-r-package@v2
        with:
          upload-snapshots: true
          error-on: '"error"'

  test-coverage:
    runs-on: ubuntu-latest
    needs: R-CMD-check # Only run if R-CMD-check passes
    steps:
      - uses: actions/checkout@v4
      - uses: r-lib/actions/setup-r@v2
      - name: Install renv
        run: |
          install.packages("renv")
        shell: Rscript {0}
      - name: Cache renv dependencies
        uses: actions/cache@v4
        with:
          path: ${{ env.R_RENV_PATHS_ROOT || '~/.local/share/renv' }}
          key: ${{ runner.os }}-renv-${{ hashFiles('renv.lock') }}
          restore-keys: ${{ runner.os }}-renv-
      - name: Restore renv dependencies
        run: |
          renv::restore()
        shell: Rscript {0}
      - uses: r-lib/actions/setup-r-dependencies@v2
        with:
          extra-packages: any::covr
          needs: coverage
      - name: Install ShannonR
        run: |
          R CMD INSTALL .
        shell: bash
      - name: Run test coverage
        run: |
          covr::codecov(quiet = FALSE)
        shell: Rscript {0}
      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v4
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
