name: R

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

permissions:
  contents: read

jobs:
  build:
    runs-on: macos-latest
    strategy:
      matrix:
        config:
          - r-version: '4.1.1'
          - r-version: '4.5.1'
          - r-version: 'devel'
          - r-version: 'devel'
            bioc: true

    steps:
      - uses: actions/checkout@v4

      - name: Set up R ${{ matrix.config.r-version }}
        uses: r-lib/actions/setup-r@v2
        with:
          r-version: ${{ matrix.config.r-version }}

      - name: Install renv and restore environment
        run: |
          install.packages("renv")
          renv::restore()
          if (!requireNamespace("rcmdcheck", quietly = TRUE)) {
            renv::install("rcmdcheck")
          }
        shell: Rscript {0}

      - name: Check
        run: rcmdcheck::rcmdcheck(args = "--no-manual", error_on = "error")
        shell: Rscript {0}
